### PR TITLE
HIL interface node

### PR DESCRIPTION
**Pull request by pvechersky**
A package for converting the sensor data coming from RotorS' gazebo plugins into MAVLink-type message that can be forwarded to the PX4 autopilot via MAVROS.

### CODE REVIEW

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+static constexpr double kDefaultGpsFrequency = 5.0;
+static const std::string kDefaultAirSpeedSubTopic = "air_speed";
+static const std::string kDefaultGroundSpeedSubTopic = "ground_speed";
+static const std::string kDefaultPressureSubTopic = "air_pressure";
+
+/// \brief Convert ros::Time into single value in microseconds.
+/// \param[in] rostime Time, in ROS format, to be converted.
+/// \return Time in microseconds.
+inline u_int64_t RosTimeToMicroseconds(const ros::Time& rostime) {
+  return (static_cast<u_int64_t>(rostime.nsec) * 1e-3 +
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: `static_cast<u_int64_t>(rostime.nsec * 1e-3)`

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+  HilListeners hil_listeners_;
+
+  /// Mutex lock for thread safety of reading hil data.
+  boost::mutex mtx_;
+};
+
+class HilSensorLevelInterface : public HilInterface {
+ public:
+  /// \brief Constructor
+  /// \param[in] q_S_B Quaternion rotation from body frame to NED frame.
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: Is the NED frame an inertial frame? or is it rigidly attached to the body?

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+  mavlink_hil_gps_t hil_gps_msg_;
+
+  /// MAVLINK HIL_SENSOR message.
+  mavlink_hil_sensor_t hil_sensor_msg_;
+
+  /// Interval between outgoing HIL_GPS messages.
+  u_int32_t gps_interval_nsec_;
+
+  /// Nanosecond portion of the last HIL_GPS message timestamp.
+  u_int32_t last_gps_pub_time_nsec_;
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: u_int64_t?

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+namespace rotors_hil {
+// Default values
+static constexpr bool kDefaultSensorLevelHil = true;
+static constexpr double kDefaultHilFrequency = 100.0;
+static constexpr double kDefaultBodyToSensorsRoll = M_PI;
+static constexpr double kDefaultBodyToSensorsPitch = 0.0;
+static constexpr double kDefaultBodyToSensorsYaw = 0.0;
+static const std::string kDefaultActuatorsPubTopic = "gazebo/command/motor_speed";
+static const std::string kDefaultMavlinkPubTopic = "/mavlink/to";
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h]: absolute namespace intended? what if you have more than one MAV?

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+static const std::string kDefaultHilControlsSubTopic = "/mavros/hil_controls/hil_controls";
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h]: same

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+  HilData() :
+      temperature(kTemperature),
+      eph(kHDOP),
+      epv(kVDOP),
+      cog(kUnknown),
+      satellites_visible(kSatellitesVisible) {}
+
+  Eigen::Quaterniond att;      // Attitude quaternion
+  Eigen::Vector3f acc;         // Linear acceleration (m/s^2)
+  Eigen::Vector3f gyro;        // Angular speed in body frame (rad / sec)
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Angular rate

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 7]
```diff
@@ -0,0 +1,209 @@
...
+struct HilData {
+  HilData() :
+      temperature(kTemperature),
+      eph(kHDOP),
+      epv(kVDOP),
+      cog(kUnknown),
+      satellites_visible(kSatellitesVisible) {}
+
+  Eigen::Quaterniond att;      // Attitude quaternion
+  Eigen::Vector3f acc;         // Linear acceleration (m/s^2)
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: float intended?

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 8]
```diff
@@ -0,0 +1,209 @@
...
+    // ROS fluid pressure sensor message is in Pascals, while
+    // MAVLINK HIL_SENSOR message measures fluid pressure in millibar.
+    // 1 Pascal = 0.01 millibar
+    float pressure_mbar = pressure_msg->fluid_pressure * kPascalToMillibar;
+    hil_data->pressure_abs = pressure_mbar;
+
+    // From the following formula: p_stag - p_static = 0.5 * rho * v^2
+    // HIL air speed is in cm/s and is converted to m/s for the purpose of
+    // computing pressure.
+    hil_data->pressure_diff = 0.5 * kAirDensity * hil_data->ind_airspeed *
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: is it guaranteed, that hil_data->ind_airspeed is set before?

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 9]
```diff
@@ -0,0 +1,209 @@
...
+                                    mag_msg->magnetic_field.z) * kTeslaToGauss;
+  }
+
+  /// \brief Callback for handling Air Pressure messages.
+  /// \param[in] pressure_msg An Air Pressure message.
+  /// \param[out] hil_data Pointer to latest data collected for HIL publishing.
+  void PressureCallback(const sensor_msgs::FluidPressureConstPtr &pressure_msg,
+                        HilData* hil_data) {
+    boost::mutex::scoped_lock lock(mtx_);
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: check if hil_data is valid pointer
i.e. `assert(hil_data);`

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 10]
```diff
@@ -0,0 +1,209 @@
...
+  HilListeners() {}
+  virtual ~HilListeners() {}
+
+  /// \brief Callback for handling Air Speed messages.
+  /// \param[in] air_speed_msg An Air Speed message.
+  /// \param[out] hil_data Pointer to latest data collected for HIL publishing.
+  void AirSpeedCallback(const geometry_msgs::TwistStampedConstPtr& air_speed_msg,
+                        HilData* hil_data) {
+    boost::mutex::scoped_lock lock(mtx_);
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: check if hil_data is valid pointer
i.e. `assert(hil_data);`

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 11]
```diff
@@ -0,0 +1,209 @@
...
+            kFix3D : kFixNone;
+  }
+
+  /// \brief Callback for handling Ground Speed messages.
+  /// \param[in] ground_speed_msg A ground speed message.
+  /// \param[out] hil_data Pointer to latest data collected for HIL publishing.
+  void GroundSpeedCallback(const geometry_msgs::TwistStampedConstPtr &ground_speed_msg,
+                           HilData* hil_data) {
+    boost::mutex::scoped_lock lock(mtx_);
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: check if hil_data is valid pointer
i.e. `assert(hil_data);`

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 12]
```diff
@@ -0,0 +1,209 @@
...
+    hil_data->vel = hil_data->gps_vel.norm();
+  }
+
+  /// \brief Callback for handling IMU messages.
+  /// \param[in] imu_msg An IMU message.
+  /// \param[out] hil_data Pointer to latest data collected for HIL publishing.
+  void ImuCallback(const sensor_msgs::ImuConstPtr& imu_msg,
+                   HilData* hil_data) {
+    boost::mutex::scoped_lock lock(mtx_);
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: check if hil_data is valid pointer
i.e. `assert(hil_data);`

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 13]
```diff
@@ -0,0 +1,209 @@
...
+                                     imu_msg->angular_velocity.z);
+  }
+
+  /// \brief Callback for handling Magnetometer messages.
+  /// \param[in] mag_msg A Magnetometer message.
+  /// \param[out] hil_data Pointer to latest data collected for HIL publishing.
+  void MagCallback(const sensor_msgs::MagneticFieldConstPtr &mag_msg,
+                   HilData* hil_data) {
+    boost::mutex::scoped_lock lock(mtx_);
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: check if hil_data is valid pointer
i.e. `assert(hil_data);`

File: rotors_hil_interface/src/hil_sensor_level_interface.cpp [hunk 14]
```diff
@@ -0,0 +1,160 @@
...
+  std::string gps_sub_topic;
+  std::string ground_speed_sub_topic;
+  std::string imu_sub_topic;
+  std::string mag_sub_topic;
+  std::string pressure_sub_topic;
+
+  pnh.param("gps_frequency", gps_freq, kDefaultGpsFrequency);
+  pnh.param("air_speed_topic", air_speed_sub_topic, kDefaultAirSpeedSubTopic);
+  pnh.param("gps_topic", gps_sub_topic, std::string(mav_msgs::default_topics::GPS));
+  pnh.param("ground_speed_topic", ground_speed_sub_topic, kDefaultGroundSpeedSubTopic);
```
Comment (burrimi) [inline rotors_hil_interface/src/hil_sensor_level_interface.cpp]: maybe we should add these defaults to mav_msgs?

File: rotors_hil_interface/src/hil_sensor_level_interface.cpp [hunk 15]
```diff
@@ -0,0 +1,160 @@
...
+  pnh.param("imu_topic", imu_sub_topic, std::string(mav_msgs::default_topics::IMU));
+  pnh.param("mag_topic", mag_sub_topic, std::string(mav_msgs::default_topics::MAGNETIC_FIELD));
+  pnh.param("pressure_topic", pressure_sub_topic, kDefaultPressureSubTopic);
+
+  // Compute the desired interval between published GPS messages.
+  gps_interval_nsec_ = kSecToNsec / gps_freq;
```
Comment (burrimi) [inline rotors_hil_interface/src/hil_sensor_level_interface.cpp]: static_cast

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h [hunk 16]
```diff
@@ -0,0 +1,133 @@
...
+/// \return Time in microseconds.
+inline u_int64_t RosTimeToMicroseconds(const ros::Time& rostime) {
+  return (static_cast<u_int64_t>(rostime.nsec) * 1e-3 +
+          static_cast<u_int64_t>(rostime.sec) * 1e6);
+}
+
+class HilInterface {
+ public:
+  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
+
```
Comment (burrimi) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: `virtual ~HilInterface();`
you need a virtual destructor in the base class

File: rotors_hil_interface/src/hil_state_level_interface.cpp [hunk 17]
```diff
@@ -0,0 +1,115 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+#include "rotors_hil_interface/hil_interface.h"
+
+namespace rotors_hil {
+
+HilStateLevelInterface::HilStateLevelInterface(const Eigen::Quaterniond q_S_B) {
```
Comment (burrimi) [inline rotors_hil_interface/src/hil_state_level_interface.cpp]: `const Eigen::Quaterniond&`

File: rotors_hil_interface/src/hil_state_level_interface.cpp [hunk 18]
```diff
@@ -0,0 +1,115 @@
...
+  boost::mutex::scoped_lock lock(mtx_);
+
+  ros::Time current_time = ros::Time::now();
+  uint64_t time_usec = RosTimeToMicroseconds(current_time);
+
+  mavlink_message_t mmsg;
+  std::vector<mavros_msgs::Mavlink> hil_msgs;
+
+  // Rotate the attitude into NED frame
+  Eigen::Quaterniond att = hil_data_.att * q_S_B_;
```
Comment (burrimi) [inline rotors_hil_interface/src/hil_state_level_interface.cpp]: Why post multiply?

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 8 above)
Comment (pvechersky) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: It should be initialized as zero but I explicitly added that to the struct constructor

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 7 above)
Comment (pvechersky) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: In the MAVLink message spec (https://pixhawk.ethz.ch/mavlink/#HIL_SENSOR) most of these fields are floats so I figured I'd store them as floats here as well. Or should I change this to double on my side?

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h (hunk 2 above)
Comment (pvechersky) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: I believe the NED frame is rigidly attached to the body

**Comment by pvechersky** [comment]
@burrimi 

New commit with most of the suggestions addressed and some clarified via comments in this pull request

**Comment by ffurrer** [comment]
Test this please.

**Comment by ffurrer** [comment]
OSX build is failing due to libmavconn not compiling (https://github.com/mavlink/mavros/blob/master/libmavconn/include/mavconn/thread_utils.h), there's an issue with different APIs for `pthread_setname_np`, see: 
http://stackoverflow.com/questions/2369738/can-i-set-the-name-of-a-thread-in-pthreads-linux/7989973#7989973

Should we propose a fix there?

**Comment by pvechersky** [comment]
@ffurrer 

Thank you for testing this and finding the information! I'm sure OSX support for libmavconn would be a nice feature going forward for them.

Would we propose it to them by opening an issue with the same links as you provided or by implementing it ourselves and opening a pull request?

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 19]
```diff
@@ -0,0 +1,222 @@
...
+#include <ros/ros.h>
+#include <sensor_msgs/FluidPressure.h>
+#include <sensor_msgs/Imu.h>
+#include <sensor_msgs/MagneticField.h>
+#include <sensor_msgs/NavSatFix.h>
+
+namespace rotors_hil {
+// Constants
+static constexpr float kAirDensity = 1.18;
+static constexpr float kGravityMagnitude = 9.8068;
```
Comment (hitimo) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Is this the only place where these constants are defined? Just to avoid having e.g. different gravity values for the same simulation session..

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 20]
```diff
@@ -0,0 +1,222 @@
...
+      eph(kHDOP),
+      epv(kVDOP),
+      cog(kUnknown),
+      ind_airspeed(0),
+      satellites_visible(kSatellitesVisible) {}
+
+  Eigen::Quaterniond att;      // Attitude quaternion
+  Eigen::Vector3f acc;         // Linear acceleration (m/s^2)
+  Eigen::Vector3f gyro;        // Angular rate in body frame (rad / sec)
+  Eigen::Vector3f mag;         // Magnetic field (Gauss)
```
Comment (hitimo) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Consider adding unit to variable name:
```
magnetic_field_gauss
```
Same applies for variables above and below.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h [hunk 21]
```diff
@@ -0,0 +1,222 @@
...
+static constexpr int kUnknown = 65535;
+
+// Conversions
+static constexpr float kDegreesToHil = 1e7;
+static constexpr float kFeetToMeters = 0.3048;
+static constexpr float kMetersToCm = 100.0;
+static constexpr float kMetersToMm = 1000.0;
+static constexpr float kPascalToMillibar = 0.01;
+static constexpr float kPressureToAltExp = 0.190284;
+static constexpr float kPressureToAltMult = 145366.45;
```
Comment (hitimo) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: units?

File: rotors_hil_interface/package.xml [hunk 22]
```diff
@@ -0,0 +1,32 @@
+<?xml version="1.0"?>
+<package>
```
Comment (hitimo) [inline rotors_hil_interface/package.xml]: why not using `<package format="2">` and `<depend>` instead of `<*_depend>`?

Comment (pvechersky) [inline rotors_hil_interface/package.xml]: Currently, all other RotorS packages use the older format, so I wanted to be consistent with that. We should probably change all the packages to use the new format at some point.

**Comment by pvechersky** [comment]
@ffurrer, I opened an issue with MAVROS to fix the compilation of libmavconn on OSX (https://github.com/mavlink/mavros/issues/626)

**Comment by ffurrer** [comment]
@pvechersky great and thanks.

**Comment by ffurrer** [comment]
test this please.

**Comment by ffurrer** [comment]
Jenkins is still complaining that there is no future module. 

>>/usr/bin/env PYTHONPATH="/home/jenkins/workspace/rotors_simulator/label/ubuntu-xenial-test/src/dependencies/mavlink-gbp-release:/opt/ros/kinetic/lib/python2.7/dist-packages" /usr/bin/python /home/jenkins/workspace/rotors_simulator/label/ubuntu-xenial-test/src/dependencies/mavlink-gbp-release/pymavlink/tools/mavgen.py --lang=C --wire-protocol=1.0 --output=include/v1.0 /home/jenkins/workspace/rotors_simulator/label/ubuntu-xenial-test/src/dependencies/mavlink-gbp-release/message_definitions/v1.0/ardupilotmega.xml
Traceback (most recent call last):
  File "/home/jenkins/workspace/rotors_simulator/label/ubuntu-xenial-test/src/dependencies/mavlink-gbp-release/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/jenkins/workspace/rotors_simulator/label/ubuntu-xenial-test/src/dependencies/mavlink-gbp-release/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
**ImportError: No module named future**

**Comment by ffurrer** [comment]
@pvechersky do you know if [this](https://pypi.python.org/pypi/future) is the missing package?

**Comment by philipoe** [comment]
@ffurrer @pvechersky  What is the status on this merge?

**Comment by ZacharyTaylor** [comment]
test this please

**Comment by ffurrer** [comment]
hmm, I'm unsure of what the issue on Jenkins exactly is, also the error changed since we last tried to compile it. We compiled it on Zac's machine and it worked fine there.
Will try to figure it out tomorrow.

**Comment by ffurrer** [comment]
restest this please

**Comment by ffurrer** [comment]
ok builds now on the ubuntu machines, @gbmhunter can we try to address the remaining comments, such that we can merge this. (@pvechersky just pinging you to let you know that we are trying to finally merge this :))

**Comment by gbmhunter** [comment]
@ffurrer o.k. what do you want me to do? Shall I do all the small things mentioned above such as adding units to variables names and adding asserts?

**Comment by ffurrer** [comment]
@gbmhunter yup, that would be great.

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h (hunk 16 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: This is now present.

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h (hunk 1 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: Done.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 13 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: ROS_ASSERT() has been added.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 9 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: ROS_ASSERT() has been added.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 8 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Resolved.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 21 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: @hitimo , @ffurrer couldn't find anything in the Google style guide for units, so followed the recommendations at http://stackoverflow.com/questions/27023406/style-for-physics-units-in-variable-names

**Comment by gbmhunter** [comment]
@pvechersky 
In `hil_listeners.h`:
`float pressure_alt; // Altitude calculated from pressure`

Is this altitude in units of meters?

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 20 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Done.

**Comment by gbmhunter** [comment]
O.K. @ffurrer , @pvechersky  I just created a pull request at https://github.com/pvechersky/rotors_simulator/pull/3 to implement these recommendations.

As I was doing so, I noticed there is the option of allowing people with write access to the base branch to be able to write to the head branch in a merge request. Which means I could of probably just made the changes in situ rather than creating this whole new pull request. Wooops! Next time...

**Comment by philipoe** [comment]
Ahhhh, @gbmhunter @ffurrer any progress? We really should get that into rotors now ;)

**Comment by gbmhunter** [comment]
I have made a pull-request with the proposed changes at https://github.com/pvechersky/rotors_simulator/pull/3, waiting on @pvechersky to accept. Note as mentioned above this probably wasn't the best way to go about it. Perhaps I could re-implement the changes on this branch directly? @ffurrer ?

**Comment by ffurrer** [comment]
@gbmhunter, as far as I know, github allows to directly push to branches on remote repos that are forked and where a pull-request is open. So you could probably try to do this and then we can merge it on our side.

**Comment by gbmhunter** [comment]
@ffurrer o.k. will do.

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface.h (hunk 3 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface.h]: Changed to `uint64_t`.

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h (hunk 4 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h]: `kDefaultActuatorsPubTopic` is no longer present in file. I'm not knowledgeable enough on the MAVlink ones to make a call on this.

File: rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h (hunk 6 above)
Comment (gbmhunter) [inline rotors_hil_interface/include/rotors_hil_interface/hil_listeners.h]: Fixed.

File: rotors_hil_interface/src/hil_sensor_level_interface.cpp (hunk 15 above)
Comment (gbmhunter) [inline rotors_hil_interface/src/hil_sensor_level_interface.cpp]: Added.

File: rotors_hil_interface/src/hil_state_level_interface.cpp (hunk 17 above)
Comment (gbmhunter) [inline rotors_hil_interface/src/hil_state_level_interface.cpp]: Fixed.

**Comment by gbmhunter** [comment]
@ffurrer o.k. I think I have done all of the requested changes above, except for the topic naming issue (I don't know exactly what the design intent is here). Also build is still failing on Jenkins, does that need to be fixed first?

File: rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h (hunk 4 above)
Comment (ffurrer) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h]: Can you use this: https://github.com/ethz-asl/mav_comm/blob/master/mav_msgs/include/mav_msgs/default_topics.h#L37?

Comment (ffurrer) [inline rotors_hil_interface/include/rotors_hil_interface/hil_interface_node.h]: You can also take a look at this: https://github.com/ethz-asl/rotors_simulator/blob/master/rotors_gazebo_plugins/src/gazebo_imu_plugin.cpp#L72 for instance.

**Comment by ffurrer** [comment]
@gbmhunter It should at least compile on the ubuntu machines on jenkins. You added the units also to the members of the messages but didn't change the messages:

```
'mavlink_hil_gps_t {aka struct __mavlink_hil_gps_t}' has no member named 'lat_1e7deg'
     hil_gps_msg_.lat_1e7deg = hil_data_.lat_1e7deg;
```
Can you undo these or adapt the messages?

**Comment by gbmhunter** [comment]
@ffurrer Woops, that will teach me for trusting eclipse's refactor to get things right. O.k. yes am doing. I will  the unit postfixes on the `HilData` type, as that's defined within the package. I won't touch the MAVlink data types as they are outside of our control.

**Comment by gbmhunter** [comment]
O.k. @ffurrer , Ubuntu tests are now passing.

**Comment by ckchow** [comment]
This fork / branch doesn't seem to build on my Ubuntu 16.04 install. Getting lots of errors like:

```
/home/chris/projects/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:105:5: error: ‘hil_gps_msg_’ was not declared in this scope
/home/chris/projects/catkin_ws/src/rotors_simulator/rotors_hil_interface/src/hil_sensor_level_interface.cpp:119:5: error: ‘mavlink_hil_gps_t’ was not declared in this scope
[...]
```

Am I missing a package? These things look like they are defined in mavlink_msg_hil_gps.h (from the mavlink c library) but aren't being included or something.

**Comment by ffurrer** [comment]
@ckchow I think it should now, at least it builds on our jenkins instances. (we were discussing your mentioned issues just before you commented).

**Comment by gbmhunter** [comment]
Hmmm, yes, the like of `mavlink_hil_gps_t` is declared/defined in the MAVlink library. Noticing it can't find the declaration, not the definition, this does look like an include issue.

Maybe the CMake file is not adding the appropriate MAVlink directory to the list of folders the compiler scans for include files from. @pvechersky ?

**Comment by pvechersky** [comment]
Sorry guys for being so MIA, I've been all over the place in the last month and a half :(

To address the latest issue: unfortunately I don't have Ubuntu 16.04 currently running so I am not readily able to test and reproduce this issue. However, one factor affecting how the MAVROS and MAVLINK directories might be getting linked is how they get installed? Either, (1) compiling from source after pulling from Github, or (2) installing MAVROS using 'sudo apt-get install ...', which should install MAVLINK as well I believe ... could this be the difference?

@ckchow Are you using the latest, Jade, version of MAVROS with Ubuntu 16.04? I'm not too familiar with such configuration unfortunately ...

**Comment by ckchow** [comment]
I'm on Ubuntu 16.04, installed mavros and its dependencies via apt-get into the system ROS directory in /opt/ros/kinetic/share/mavros.

ros-kinetic-{mavros, mavros-extras, mavros-msgs}: 0.18.5 
ros-kinetic-libmavconn: 0.18.5
ros-kinetic-mavlink: 2016.12.12

I believe cmake is finding these packages ok since I am able to include other headers from them. I tried including mavlink/v2/common.hpp (or something like that) but I would get lots of other crazy macro expansion errors. Is this possibly a kinetic issue?

**Comment by ckchow** [comment]
I was poking around the include directories for libmavconn (which is a dependency of mavros, in turn a dependency for rotors), and it looks like the newest version of mavros compiles libmavconn with support only for v2 of the mavlink protocol. I'm going to try to update the includes in rotors to refer to the HIL interface in mavlink v2. 

@pvechersky What version of mavros / libmavconn are you using in your builds?

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
mavros builds now on osx with https://github.com/mavlink/mavros/pull/650.

**Comment by hitimo** [comment]
@ckchow This combination works for Ubuntu 14.04 + ROS Indigo:
```
MAVROS: git@github.com:mavlink/mavros.git @ indigo-devel
MAVLINK: git@github.com:mavlink/mavlink-gbp-release.git @ debian/kinetic/mavlink
```
Also have a look at [this wiki entry](https://github.com/ethz-asl/rotors_simulator/wiki/Setting-up-RotorS-as-Fixed-Wing-HiL-Simulation-(Pixhawk,-Mavros,-Mavlink,-QGC)).

**Comment by hitimo** [comment]
@ffurrer nice

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
test this please

**Comment by hitimo** [comment]
lgtm :)

**Comment by burrimi** [comment]
lgtm.

**Comment by philipoe** [comment]
@ffurrer Do you merge this?
