### ISSUE TITLE
Errors while building rotors_gazebo_plugins

### ISSUE THREAD

**Issue by kpiyush25** [ethz-asl/rotors_simulator#653]
I am trying to use fixed wing in rotors simulator and the branch is feature/fw_hil_rotors but while building the package I'm getting the following errors:

```bash
/home/piyush/ros_ws2/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp: In member function ‘void
 gazebo::GazeboMavlinkInterface::VaneCallback(gazebo::VanePtr&)’: /home/piyush/ros_ws2/src/rotors_simulator
`/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp:988:3:` error: ‘mavlink_hil_extended_t’ was not declared in this scope
 mavlink_hil_extended_t hil_extended_msg; ^~~~~~~~~~~~~~~~~~~~~~ /home/piyush/ros_ws2/src/rotors_simulator
/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp:988:3: note: suggested alternative: ‘mavlink_hil_sensor_t’ 
mavlink_hil_extended_t hil_extended_msg; ^~~~~~~~~~~~~~~~~~~~~~ mavlink_hil_sensor_t /home/piyush/ros_ws2
/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp:991:3: error: ‘hil_extended_msg’ was not
 declared in this scope hil_extended_msg.timestamp = world_->SimTime().Double() * 1e6; ^~~~~~~~~~~~~~~~ /home/piyush
/ros_ws2/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp:1006:3: error: 
‘mavlink_msg_hil_extended_encode_chan’ was not declared in this scope mavlink_msg_hil_extended_encode_chan(1, 200, 
MAVLINK_COMM_0, &msg, &hil_extended_msg); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /home/piyush/ros_ws2
/src/rotors_simulator/rotors_gazebo_plugins/src/gazebo_mavlink_interface.cpp:1006:3: note: suggested alternative: 
‘mavlink_msg_hil_sensor_encode_chan’ mavlink_msg_hil_extended_encode_chan(1, 200, MAVLINK_COMM_0, &msg, 
&hil_extended_msg); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mavlink_msg_hil_sensor_encode_chan make[2]: *** 
[CMakeFiles/rotors_gazebo_mavlink_interface.dir/src/gazebo_mavlink_interface.cpp.o] Error 1 make[2]: *** Waiting for 
unfinished jobs.... make[1]: *** [CMakeFiles/rotors_gazebo_mavlink_interface.dir/all] Error 2 make[1]: *** Waiting for unfinished 
jobs.... make: *** [all] Error 2 
```

Please help me in correcting this particular error or if it is still being updated then also let me know what can be done.
I am using Gazebo version 9.14.0 and ROS melodic running on Ubuntu version 18.04 
Thanks in advance!

**Comment by Jaeyoung-Lim** [comment]
@kpiyush25 Your mavlink version is not compatible with `fw_hil_rotors`. Given that you don't have `mavlink_msg_hil_extended_encode_chan` your mavlink `c_library_v2` is too old. 

This repository builds on Ubuntu 18.04 (ROS melodic) with Gazebo 9. If in doubt, check build results of https://github.com/ethz-asl/rotors_simulator/pull/651
